const config = {
  BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  AWS_REGION: process.env.NEXT_PUBLIC_AWS_REGION,
  AWS_ACCESS_KEY_ID: process.env.NEXT_PUBLIC_AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.NEXT_PUBLIC_AWS_SECRET_KEY,
  AWS_KEY_ID: process.env.NEXT_PUBLIC_AWS_KEY_ID,
  GOOGLE_API_KEY: process.env.NEXT_PUBLIC_GOOGLE_API_KEY,
  GOOGLE_ANALYTICS_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS,
};

export default config;
